version: 2.1
default: &default
    docker:
      - image: circleci/node:10.15-browsers
    working_directory: ~/repo
commands:
  prepare:
    description: "Prepare working directory"
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
jobs:
  test:
    <<: *default
    steps:
      - prepare
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run tests
          command: npm run test
  deploy:
    <<: *default
    steps:
      - prepare
      - run:
          name: Bump version
          command: |
            git config user.email circleci@circleci
            git config user.name CircleCI
            git checkout -- package-lock.json
            npm version patch -m "patch version bump [ci skip]"
            git push
            git push --tags
      - run:
          name: Publish
          command: |
            git clone $CIRCLE_REPOSITORY_URL out
            cd out
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .
            cd ..
            npm run build
            cp -a www/. out/.
            mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
            cd out
            echo "checkout.certitrade.se" > CNAME
            git config user.name "$USER_NAME"
            git config user.email "$USER_EMAIL"
            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
            git push origin gh-pages
workflows:
  version: 2.1
  build-flow:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
